### ISSUE TITLE
Validação de tamanho para a imagem de cover da Startup

### ISSUE THREAD

**Issue by patrickemuller** [LISTABETA/LISTABETA#34]
Deve-se validar o tamanho mínimo de imagem de Cover da Startup.
Validar o tamanho ajudará a corrigir problemas com imagens distorcidas dentro da plataforma atual.
@cbgabe pode dizer melhor qual as dimensões apropriadas da imagem.

**Comment by gabeborges** [comment]
@patrickemuller a dimensão correta é 1080px de largura por 810px de altura.

**Comment by patrickemuller** [comment]
Esta tarefa já foi realizada no PR #40. Vou realizar o fechamento dessa Issue.
